version: "3.7"

services:
  latex:
    image: "ghcr.io/peaceiris/latex:v1.1.0-full"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/bruno/git/hacklab/Notes/AD:/app
    security_opt:
      - no-new-privileges:true